(* This file was generated by Eliom-distillery.
   Feel free to use it, modify it, and redistribute it as you wish. *)

[%%shared
[@@@ocaml.warning "-27-34-37-69-33"]
]

let%server application_name = "h42n42"
let%client application_name = Eliom_client.get_application_name ()

let%server () =
  Ocsipersist_settings.set_db_file "local/var/data/h42n42/h42n42_db"

module%shared App = Eliom_registration.App (struct
  let application_name = application_name
  let global_data_path = Some ["__global_data__"]
end)

let%client _ = Eliom_client.persist_document_head ()

let%server main_service =
  Eliom_service.create
    ~path:(Eliom_service.Path [])
    ~meth:(Eliom_service.Get Eliom_parameter.unit)
    ()
let%client main_service = ~%main_service

[%%shared
type state = Healthy | Infected | Dead
type kind  = Normal  | Mean     | Berserk
]

module%client Const = struct
  let base_size     = 40.0
  let mean_scale    = 0.85
  let berserk_max   = 4.0
  let infection_life= 15.0
end

module%client Params = struct
  let infection_prob  = ref 0.02
  let jitter_prob     = ref 0.02
  let turn_min_s      = ref 2.0
  let turn_max_s      = ref 5.0
  let reproduce_min   = ref 12.0
  let reproduce_max   = ref 22.0
  let max_creets      = ref 40
  let river_h         = ref 60.0
  let hospital_h      = ref 80.0
  let difficulty_step = ref 0.01
  let initial_creets  = ref 14
  let slow_on_infect  = 0.85
end

module%client Difficulty = struct
  let base = ref 1.0
  let running = ref false
  let start () =
    if not !running then (
      running := true;
      Lwt.async (fun () ->
        let rec loop () =
          let%lwt () = Js_of_ocaml_lwt.Lwt_js.sleep 0.5 in
          base := min 3.0 (!base +. !(Params.difficulty_step));
          loop ()
        in
        loop ()
      )
    )
end

module%client Config = struct
  let paused = ref false
end

module%client Runtime = struct
  let game_over    = ref false
  let game_started = ref false
  let rec wait_unpaused () =
    if !(Config.paused) || !game_over || not !game_started then (
      let%lwt () = Js_of_ocaml_lwt.Lwt_js.sleep 0.05 in
      wait_unpaused ()
    ) else Lwt.return_unit
end

module%client Session = struct
  let epoch = ref 0
end

module%client Callbacks = struct
  let on_replay : (unit -> unit) ref = ref (fun () -> ())
end

(* ─────────────────────────────────────────────────────────────────────────── *)
module%client Creet = struct
  open Js_of_ocaml

  type t = {
    id       : int;
    epoch    : int;
    mutable x: float;
    mutable y: float;
    mutable vx: float;
    mutable vy: float;
    mutable state: state;
    mutable kind: kind;
    mutable size_scale: float;
    mutable life_left: float option;
    mutable grabbed: bool;
    mutable next_turn: float;
    elt      : Dom_html.divElement Js.t;
  }

  let size (c:t) = Const.base_size *. c.size_scale
  let radius (c:t) = (size c) /. 2.0
  let center (c:t) = (c.x +. radius c, c.y +. radius c)

  let class_string (c:t) =
    let st = match c.state with Healthy -> "healthy" | Infected -> "infected" | Dead -> "dead" in
    let kd = match c.kind  with Normal  -> "normal"  | Mean     -> "mean"     | Berserk -> "berserk" in
    let grabbed = if c.grabbed then " grabbed" else "" in
    Printf.sprintf "creet %s %s%s" st kd grabbed

  let apply_classes (c:t) =
    c.elt##.className := Js.string (class_string c)

  let apply_visual (c:t) =
    let sz = size c |> int_of_float in
    c.elt##.style##.width  := Js.string (Printf.sprintf "%dpx" sz);
    c.elt##.style##.height := Js.string (Printf.sprintf "%dpx" sz);
    c.elt##.style##.left   := Js.string (Printf.sprintf "%dpx" (int_of_float c.x));
    c.elt##.style##.top    := Js.string (Printf.sprintf "%dpx" (int_of_float c.y));
    apply_classes c

  let make_dom ~id ~x:_ ~y:_ =
    let elt =
      Js_of_ocaml_tyxml.Tyxml_js.Html.(
        div ~a:[ a_id (Printf.sprintf "creet-%d" id); a_class ["creet"; "healthy"; "normal"] ] []
      )
    in
    Js_of_ocaml_tyxml.Tyxml_js.To_dom.of_div elt

  let rand_vel ?(speed=1.2) () =
    let angle = 6.283185307179586 *. Random.float 1.0 in
    (speed *. cos angle, speed *. sin angle)

  let create ~id ~x ~y () =
    let elt = make_dom ~id ~x ~y in
    let sim = Dom_html.getElementById "sim" in
    sim##appendChild (elt :> Dom.node Js.t) |> ignore;
    let vx, vy = rand_vel () in
    let c = {
      id; epoch = !Session.epoch;
      x; y; vx; vy;
      state = Healthy; kind = Normal;
      size_scale = 1.0; life_left=None; grabbed=false;
      next_turn = !(Params.turn_min_s) +. Random.float (!(Params.turn_max_s) -. !(Params.turn_min_s));
      elt
    } in
    apply_visual c; c

  let set_size_scale (c:t) (s:float) =
    let old_r = radius c in
    c.size_scale <- s;
    let new_r = radius c in
    c.x <- c.x -. (new_r -. old_r);
    c.y <- c.y -. (new_r -. old_r);
    apply_visual c

  let heal (c:t) =
    if c.state = Infected then (
      c.state <- Healthy;
      c.kind <- Normal;
      c.life_left <- None;
      set_size_scale c 1.0;
      c.vx <- c.vx /. Params.slow_on_infect;
      c.vy <- c.vy /. Params.slow_on_infect;
      apply_classes c
    )

  let to_berserk (c:t) =
    c.kind <- Berserk;
    c.life_left <- Some Const.infection_life;
    apply_classes c

  let to_mean (c:t) =
    c.kind <- Mean;
    set_size_scale c Const.mean_scale;
    apply_classes c

  let infect (c:t) =
    if c.state = Healthy && not c.grabbed then (
      c.state <- Infected;
      c.life_left <- Some Const.infection_life;
      c.vx <- c.vx *. Params.slow_on_infect;
      c.vy <- c.vy *. Params.slow_on_infect;
      let r = Random.float 1.0 in
      if r < 0.10 then to_berserk c
      else if r < 0.20 then to_mean c
      else apply_classes c
    )
end

module%client World = struct
  let creets : Creet.t list ref = ref []
  let add (c : Creet.t) = creets := c :: !creets
  let remove (c : Creet.t) = creets := List.filter (fun x -> x != c) !creets
  let all () = !creets
  let count () = List.length !creets
  let count_healthy () =
    List.fold_left (fun acc (c:Creet.t) -> if c.state = Healthy then acc + 1 else acc) 0 !creets
  let any_healthy () = count_healthy () > 0
end

module%client Ids = struct
  let counter = ref 1000
  let next () = incr counter; !counter
end

module%client Timer = struct
  open Js_of_ocaml
  let start_ms       : float option ref = ref None
  let paused_acc_ms  = ref 0.0
  let pause_start_ms : float option ref = ref None
  let running        = ref false

  let now_ms () = (new%js Js.date_now)##getTime
  let format (secs:int) = Printf.sprintf "%02d:%02d" (secs/60) (secs mod 60)

  let elapsed_ms () =
    match !start_ms with
    | None -> 0.0
    | Some s ->
        let base = now_ms () -. s -. !paused_acc_ms in
        match !pause_start_ms with
        | None   -> base
        | Some p -> base -. (now_ms () -. p)

  let elapsed_string () =
    let secs = max 0 (int_of_float (elapsed_ms () /. 1000.)) in
    format secs

  let start () =
    start_ms := Some (now_ms ());
    paused_acc_ms := 0.0;
    pause_start_ms := None;
    running := true;
    Lwt.async (fun () ->
      let rec loop () =
        if !running && not !(Runtime.game_over) then (
          (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "stat-time")) with
           | Some el -> el##.textContent := Js.Opt.return (Js.string (elapsed_string ()))
           | None -> ());
          let%lwt () = Js_of_ocaml_lwt.Lwt_js.sleep 0.25 in
          loop ()
        ) else Lwt.return_unit
      in loop ()
    )

  let pause () =
    match !pause_start_ms with Some _ -> () | None -> pause_start_ms := Some (now_ms ())
  let resume () =
    match !pause_start_ms with
    | None -> ()
    | Some p -> paused_acc_ms := !paused_acc_ms +. (now_ms () -. p); pause_start_ms := None
end

module%client Stats = struct
  open Js_of_ocaml
  let dead_total = ref 0

  let ensure_overlay () =
    match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "hud")) with
    | Some _ -> ()
    | None ->
        let open Js_of_ocaml_tyxml.Tyxml_js in
        let v ?(id="") init =
          Html.span ~a:[ Html.a_class ["hud__val"]; (if id="" then Html.a_class [] else Html.a_id id) ] [Html.txt init]
        in
        let wrap =
          Html.div ~a:[ Html.a_id "hud"; Html.a_class ["hud"] ] [
            Html.span [Html.txt "Time: "]; v ~id:"stat-time" "00:00"; Html.txt "  ";
            Html.span [Html.txt "Alive: "]; v ~id:"stat-alive" "0"; Html.txt "  ";
            Html.span [Html.txt "Healthy: "]; v ~id:"stat-healthy" "0"; Html.txt "  ";
            Html.span [Html.txt "Infected: "]; v ~id:"stat-infected" "0"; Html.txt "  ";
            Html.span [Html.txt "Dead: "]; v ~id:"stat-dead" "0";
          ]
        in
        let dom = Js_of_ocaml_tyxml.Tyxml_js.To_dom.of_div wrap in
        Dom.appendChild (Dom_html.document##.body :> Dom.node Js.t) (dom :> Dom.node Js.t)

  let set_text id v =
    let el = Dom_html.getElementById id in
    el##.textContent := Js.Opt.return (Js.string v)

  let refresh () =
    ensure_overlay ();
    let healthy, infected =
      List.fold_left
        (fun (h, i) (c : Creet.t) ->
          match c.Creet.state with Healthy -> (h+1,i) | Infected -> (h,i+1) | Dead -> (h,i))
        (0, 0) (World.all ())
    in
    let alive = healthy + infected in
    set_text "stat-healthy" (string_of_int healthy);
    set_text "stat-infected" (string_of_int infected);
    set_text "stat-alive" (string_of_int alive);
    set_text "stat-dead" (string_of_int !dead_total)

  let on_death () = incr dead_total; refresh ()

  let show_game_over () =
    if not !(Runtime.game_over) then (
      Runtime.game_over := true;

      (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "settings-panel")) with
       | Some sp -> sp##.classList##add (Js.string "is-hidden")
       | None -> ());
      (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "btn-menu")) with
       | Some b -> b##.classList##remove (Js.string "is-open")
       | None -> ());

      (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "gameover")) with
       | Some old -> Js.Opt.iter old##.parentNode (fun p -> ignore (Dom.removeChild p (old :> Dom.node Js.t)))
       | None -> ());

      let open Js_of_ocaml_tyxml.Tyxml_js in
      let panel =
        Html.div ~a:[ Html.a_id "gameover"; Html.a_class ["overlay"; "overlay--gameover"] ] [
          Html.div ~a:[ Html.a_class ["gameover__box"] ] [
            Html.div ~a:[ Html.a_class ["gameover__title"] ] [ Html.txt "GAME OVER" ];
            Html.div ~a:[ Html.a_class ["gameover__time"] ]  [ Html.txt ("Time: " ^ Timer.elapsed_string ()) ];
            Html.button ~a:[ Html.a_id "btn-replay"; Html.a_class ["btn"; "btn--primary"] ] [ Html.txt "Replay" ];
          ]
        ]
      in
      let dom = Js_of_ocaml_tyxml.Tyxml_js.To_dom.of_div panel in
      Dom.appendChild (Dom_html.document##.body :> Dom.node Js.t) (dom :> Dom.node Js.t);

      let btn = Js_of_ocaml.Dom_html.getElementById "btn-replay" in
      let open Js_of_ocaml_lwt in
      Lwt.async (fun () ->
        Lwt_js_events.clicks btn (fun _ _ -> (!Callbacks.on_replay) (); Lwt.return_unit))
    )
end

(* ─────────────────────────────────────────────────────────────────────────── *)
(* Bantlar (nehir/hastane) – üst/alt konumu garanti *)
module%client Bands = struct
  open Js_of_ocaml

  let set_heights () =
    (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "river")) with
     | Some d ->
         d##.style##.height := Js.string (Printf.sprintf "%dpx" (int_of_float !(Params.river_h)));
         d##.style##.top    := Js.string "0px";
         d##.style##.bottom := Js.string "auto"
     | None -> ());
    (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "hospital")) with
     | Some d ->
         d##.style##.height := Js.string (Printf.sprintf "%dpx" (int_of_float !(Params.hospital_h)));
         d##.style##.top    := Js.string "auto";
         d##.style##.bottom := Js.string "0px"
     | None -> ())

  let create_if_missing id classes =
    match Js.Opt.to_option (Dom_html.document##getElementById (Js.string id)) with
    | Some _ -> ()
    | None ->
        let d = Dom_html.createDiv Dom_html.document in
        d##.id := Js.string id; d##.className := Js.string classes;
        d##.style##.position := Js.string "absolute";
        let sim = Dom_html.getElementById "sim" in
        Dom.appendChild (sim :> Dom.node Js.t) (d :> Dom.node Js.t)

  let init () =
    create_if_missing "river" "band band--river";
    create_if_missing "hospital" "band band--hospital";
    set_heights ();
    (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "river")) with
     | Some r -> r##.style##.zIndex := Js.string "3" | None -> ());
    (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "hospital")) with
     | Some h -> h##.style##.zIndex := Js.string "2" | None -> ());
end

(* ─────────────────────────────────────────────────────────────────────────── *)
module%client Infection = struct
  let contact (a:Creet.t) (b:Creet.t) =
    let ax, ay = Creet.center a and bx, by = Creet.center b in
    let dx = ax -. bx and dy = ay -. by in
    let rr = (Creet.radius a +. Creet.radius b) in
    (dx *. dx +. dy *. dy) <= rr *. rr

  let tick_pair (a:Creet.t) (b:Creet.t) =
    if a.grabbed || b.grabbed then ()
    else match a.state, b.state with
      | Infected, Healthy ->
          if contact a b && Random.float 1.0 < !(Params.infection_prob) then Creet.infect b
      | Healthy, Infected ->
          if contact a b && Random.float 1.0 < !(Params.infection_prob) then Creet.infect a
      | _ -> ()
end

module%client Behavior = struct
  let mean_speed_boost = 1.15 /. Params.slow_on_infect
  let speed_mult (c : Creet.t) =
    match c.kind, c.state with
    | Mean,    Infected -> mean_speed_boost
    | Berserk, Infected -> 1.0
    | _ -> 1.0

  let is_alive (c : Creet.t) = c.state <> Dead

  let nearest ?(pred=(fun (_:Creet.t)->true)) (self : Creet.t) : Creet.t option =
    let sx, sy = Creet.center self in
    let best : (Creet.t * float) option ref = ref None in
    World.all ()
    |> List.iter (fun o ->
         if o != self && is_alive o && pred o then (
           let ox, oy = Creet.center o in
           let dx = sx -. ox and dy = sy -. oy in
           let d2 = dx*.dx +. dy*.dy in
           match !best with None -> best := Some (o, d2) | Some (_, bd2) -> if d2 < bd2 then best := Some (o, d2)
         ));
    match !best with Some (o, _) -> Some o | None -> None

  let nudge_towards (c : Creet.t) (tx,ty) strength =
    let cx,cy = Creet.center c in
    let dx = tx -. cx and dy = ty -. cy in
    let d  = max 0.001 (sqrt (dx *. dx +. dy *. dy)) in
    let ux, uy = dx /. d, dy /. d in
    let cur_speed = sqrt (c.vx *. c.vx +. c.vy *. c.vy) in
    let desired = max 0.6 cur_speed in
    let nx = (1. -. strength) *. c.vx +. strength *. ux *. desired in
    let ny = (1. -. strength) *. c.vy +. strength *. uy *. desired in
    c.vx <- nx; c.vy <- ny

  let update (c : Creet.t) =
    match c.state, c.kind with
    | Infected, Mean ->
        if Random.float 1.0 < 0.30 then
          (match nearest c ~pred:(fun o -> o.state = Healthy) with
           | Some t -> nudge_towards c (Creet.center t) 0.12
           | None -> ())
    | _ -> ()
end

module%client Movement = struct
  open Js_of_ocaml

  let bounds () =
    let w = float_of_int Dom_html.window##.innerWidth
    and h = float_of_int Dom_html.window##.innerHeight in
    (w, h)

  let bounce (c:Creet.t) =
    let w, h = bounds () in
    let sz = Creet.size c in
    if c.x < 0. then (c.x <- 0.; c.vx <- -. c.vx)
    else if c.x +. sz > w then (c.x <- w -. sz; c.vx <- -. c.vx);
    if c.y < 0. then (c.y <- 0.; c.vy <- -. c.vy)
    else if c.y +. sz > h then (c.y <- h -. sz; c.vy <- -. c.vy)

  let in_river (c:Creet.t) = c.y <= !(Params.river_h)
  let in_hospital (c:Creet.t) =
    let _, h = bounds () in
    (c.y +. Creet.size c) >= (h -. !(Params.hospital_h))

  let turn_tick (c:Creet.t) dt =
    c.next_turn <- c.next_turn -. dt;
    if c.next_turn <= 0. then (
      let ang = (Random.float 0.8 -. 0.4) in
      let ca = cos ang and sa = sin ang in
      let vx' = c.vx *. ca -. c.vy *. sa
      and vy' = c.vx *. sa +. c.vy *. ca in
      c.vx <- vx'; c.vy <- vy';
      c.next_turn <- !(Params.turn_min_s) +. Random.float (!(Params.turn_max_s) -. !(Params.turn_min_s))
    );
    if Random.float 1.0 < !(Params.jitter_prob) then (
      let a = (Random.float 0.6 -. 0.3) in
      let ca = cos a and sa = sin a in
      let vx' = c.vx *. ca -. c.vy *. sa
      and vy' = c.vx *. sa +. c.vy *. ca in
      c.vx <- vx'; c.vy <- vy'
    )

  let clamp x lo hi = max lo (min hi x)
  let rand_repro_delay () =
    !(Params.reproduce_min) +. Random.float (!(Params.reproduce_max) -. !(Params.reproduce_min))

  let rec reproduction_loop (parent : Creet.t) : unit Lwt.t =
    if parent.epoch <> !Session.epoch then Lwt.return_unit
    else if parent.state <> Healthy then Lwt.return_unit
    else if not (World.any_healthy ()) then Lwt.return_unit
    else (
      let%lwt () = Js_of_ocaml_lwt.Lwt_js.sleep (rand_repro_delay ()) in
      if parent.epoch = !Session.epoch
         && parent.state = Healthy
         && World.any_healthy ()
         && World.count () < !(Params.max_creets) then (
        let w = float_of_int Dom_html.window##.innerWidth
        and h = float_of_int Dom_html.window##.innerHeight in
        let dx = (Random.float 30.) -. 15. in
        let dy = (Random.float 30.) -. 15. in
        let sz = Creet.size parent in
        let x = clamp (parent.x +. dx) 0. (w -. sz)
        and y = clamp (parent.y +. dy) 0. (h -. sz) in
        let id = Ids.next () in
        let child = Creet.create ~id ~x ~y () in
        World.add child;
        start child;
        start_reproduction child;
        Stats.refresh ();
      );
      reproduction_loop parent
    )

  and start_reproduction (c : Creet.t) = Lwt.async (fun () -> reproduction_loop c)

  and loop (c : Creet.t) : unit Lwt.t =
    if c.epoch <> !Session.epoch then Lwt.return_unit
    else if c.state = Dead then Lwt.return_unit
    else (
      let%lwt () = Runtime.wait_unpaused () in
      let spd_scale = !(Difficulty.base) *. Behavior.speed_mult c in

      let died_now = ref false in
      (match c.life_left, c.state with
       | Some t, Infected ->
           let t' = t -. 0.016 in
           c.life_left <- Some t';
           (match c.kind with
            | Berserk ->
                let progress = max 0.0 (min 1.0 ((Const.infection_life -. t') /. Const.infection_life)) in
                let scale = 1.0 +. (Const.berserk_max -. 1.0) *. progress in
                Creet.set_size_scale c scale
            | _ -> ());
           if t' <= 0.0 then (
             c.state <- Dead;
             Js_of_ocaml.Js.Opt.iter c.elt##.parentNode (fun p ->
               ignore (Js_of_ocaml.Dom.removeChild p (c.elt :> Js_of_ocaml.Dom.node Js.t)));
             World.remove c;
             Stats.on_death ();
             died_now := true
           )
       | _ -> ());

      if !died_now then Lwt.return_unit
      else (
        Behavior.update c;

        if not c.grabbed then (
          turn_tick c 0.016;
          c.x <- c.x +. (c.vx *. spd_scale);
          c.y <- c.y +. (c.vy *. spd_scale);
          bounce c;
          if c.state = Healthy && in_river c then Creet.infect c
        );

        Creet.apply_visual c;

        if (World.count () = 0) || (World.count_healthy () = 0) then (
          Stats.refresh (); Stats.show_game_over (); Lwt.return_unit
        ) else (
          let%lwt () = Js_of_ocaml_lwt.Lwt_js.sleep 0.016 in
          loop c
        )
      )
    )

  and start (c : Creet.t) = Lwt.async (fun () -> loop c)
end

(* ─────────────────────────────────────────────────────────────────────────── *)
module%client Quad = struct
  type rect = { x: float; y: float; w: float; h: float }

  let contains_point (r:rect) (px,py) =
    px >= r.x && px <= r.x +. r.w && py >= r.y && py <= r.y +. r.h

  let intersects (a:rect) (b:rect) =
    not (b.x > a.x +. a.w || b.x +. b.w < a.x || b.y > a.y +. a.h || b.y +. b.h < a.y)

  type node = {
    bounds   : rect;
    capacity : int;
    mutable points : Creet.t list;
    mutable nw : node option;
    mutable ne : node option;
    mutable sw : node option;
    mutable se : node option;
    mutable divided : bool;
  }

  let create bounds capacity =
    { bounds; capacity; points=[]; nw=None; ne=None; sw=None; se=None; divided=false }

  let subdivide n =
    let hw = n.bounds.w /. 2. and hh = n.bounds.h /. 2. in
    let x = n.bounds.x and y = n.bounds.y in
    let mk x y = create { x; y; w = hw; h = hh } n.capacity in
    n.nw <- Some (mk x y);
    n.ne <- Some (mk (x +. hw) y);
    n.sw <- Some (mk x (y +. hh));
    n.se <- Some (mk (x +. hw) (y +. hh));
    n.divided <- true

  let rec insert n (c:Creet.t) =
    let px, py = Creet.center c in
    if not (contains_point n.bounds (px,py)) then false
    else if (List.length n.points) < n.capacity && not n.divided then (
      n.points <- c :: n.points; true
    ) else (
      if not n.divided then subdivide n;
      let inserted =
        (match n.nw with Some q when insert q c -> true | _ -> false)
        || (match n.ne with Some q when insert q c -> true | _ -> false)
        || (match n.sw with Some q when insert q c -> true | _ -> false)
        || (match n.se with Some q when insert q c -> true | _ -> false)
      in
      if not inserted then n.points <- c :: n.points;
      true
    )

  let rec query n (range:rect) (acc:Creet.t list ref) =
    if not (intersects n.bounds range) then ()
    else (
      List.iter (fun (c:Creet.t) ->
        let px,py = Creet.center c in
        if contains_point range (px,py) then acc := c :: !acc) n.points;
      if n.divided then (
        (match n.nw with Some q -> query q range acc | None -> ());
        (match n.ne with Some q -> query q range acc | None -> ());
        (match n.sw with Some q -> query q range acc | None -> ());
        (match n.se with Some q -> query q range acc | None -> ())
      )
    )
end

module%client Collider = struct
  open Quad
  let max_other_radius = (Const.base_size *. Const.berserk_max) /. 2.0

  let build_tree () =
    let w = float_of_int Js_of_ocaml.Dom_html.window##.innerWidth
    and h = float_of_int Js_of_ocaml.Dom_html.window##.innerHeight in
    let root = create { x=0.; y=0.; w; h } 8 in
    World.all () |> List.iter (fun (c:Creet.t) -> if c.state <> Dead then ignore (insert root c));
    root

  let process_pairs root =
    World.all ()
    |> List.iter (fun (c:Creet.t) ->
         if c.state <> Dead then (
           let cx, cy = Creet.center c in
           let r = Creet.radius c +. max_other_radius in
           let range = { x = cx -. r; y = cy -. r; w = 2. *. r; h = 2. *. r } in
           let acc : Creet.t list ref = ref [] in
           query root range acc;
           List.iter (fun (o:Creet.t) ->
             if o != c && o.id > c.id && o.state <> Dead then (
               Infection.tick_pair c o; Infection.tick_pair o c;
             )
           ) !acc
         )
       )

  let start () =
    Lwt.async (fun () ->
      let rec loop () =
        if !(Runtime.game_over) || not !(Runtime.game_started) then Lwt.return_unit
        else (
          let%lwt () = Runtime.wait_unpaused () in
          let root = build_tree () in
          process_pairs root;
          let%lwt () = Js_of_ocaml_lwt.Lwt_js.sleep 0.016 in
          loop ()
        )
      in loop ()
    )
end

module%client Input = struct
  open Js_of_ocaml

  type drag = { mutable active: bool; mutable target: Creet.t option; mutable offx: float; mutable offy: float }
  let d = { active=false; target=None; offx=0.; offy=0. }

  let element_pos (e:Dom_html.element Js.t) =
    let r = e##getBoundingClientRect in (r##.left, r##.top)

  let mouse_pos_in (e:Dom_html.element Js.t) (ev:Dom_html.mouseEvent Js.t) =
    let ex, ey = element_pos e in (float_of_int ev##.clientX -. ex, float_of_int ev##.clientY -. ey)

  let try_pick (x:float) (y:float) : Creet.t option =
    let within (c:Creet.t) =
      let cx, cy = Creet.center c in
      let r = Creet.radius c in
      let dx = x -. cx and dy = y -. cy in (dx *. dx +. dy *. dy) <= r *. r
    in
    World.all () |> List.find_opt within

  let install () =
    let sim_el = Js_of_ocaml.Dom_html.getElementById "sim" in
    let open Js_of_ocaml_lwt in

    Lwt.async (fun () ->
      Lwt_js_events.mousedowns (sim_el :> Dom_html.eventTarget Js.t) (fun ev _ ->
        if not !(Runtime.game_over) && !(Runtime.game_started) then (
          let x, y = mouse_pos_in sim_el ev in
          match try_pick x y with
          | None -> Lwt.return_unit
          | Some c ->
              d.active <- true; d.target <- Some c; c.grabbed <- true; Creet.apply_classes c;
              let cx, cy = Creet.center c in
              d.offx <- x -. cx; d.offy <- y -. cy;
              Lwt.return_unit
        ) else Lwt.return_unit));

    Lwt.async (fun () ->
      Lwt_js_events.mousemoves Dom_html.document (fun ev _ ->
        match d.target with
        | Some c when d.active ->
            let w = float_of_int Dom_html.window##.innerWidth
            and h = float_of_int Dom_html.window##.innerHeight in
            let x, y = float_of_int ev##.clientX, float_of_int ev##.clientY in
            let nx = x -. d.offx -. Creet.radius c
            and ny = y -. d.offy -. Creet.radius c in
            let nx = max 0. (min (w -. Creet.size c) nx)
            and ny = max 0. (min (h -. Creet.size c) ny) in
            c.x <- nx; c.y <- ny; Creet.apply_visual c; Lwt.return_unit
        | _ -> Lwt.return_unit));

    Lwt.async (fun () ->
      Lwt_js_events.mouseups Dom_html.document (fun _ _ ->
        match d.target with
        | Some c ->
            d.active <- false; d.target <- None; c.grabbed <- false; Creet.apply_classes c;
            if c.state = Infected && Movement.in_hospital c then Creet.heal c;
            Lwt.return_unit
        | None -> Lwt.return_unit));
    ()
end

(* ─────────────────────────────────────────────────────────────────────────── *)
module%client Settings = struct
  open Js_of_ocaml
  let make_sliders (p:Dom_html.divElement Js.t) =
    let open Js_of_ocaml_lwt in
    let set_attr (el: #Dom_html.element Js.t) k v = el##setAttribute (Js.string k) (Js.string v) in
    let add_row (p:Dom_html.divElement Js.t) (title:string)
      : Dom_html.divElement Js.t * Dom_html.element Js.t * Dom_html.inputElement Js.t =
      let doc = Dom_html.document in
      let row = Dom_html.createDiv doc in
      row##.className := Js.string "settings__row";
      let label = Dom_html.createSpan doc in
      label##.className := Js.string "settings__label";
      label##.textContent := Js.Opt.return (Js.string title);
      let value = Dom_html.createSpan doc in
      value##.className := Js.string "settings__value";
      Dom.appendChild (row :> Dom.node Js.t) (label :> Dom.node Js.t);
      Dom.appendChild (row :> Dom.node Js.t) (value :> Dom.node Js.t);
      let slider = Dom_html.createInput ~_type:(Js.string "range") doc in
      slider##.className := Js.string "settings__slider";
      Dom.appendChild (row :> Dom.node Js.t) (slider :> Dom.node Js.t);
      Dom.appendChild (p   :> Dom.node Js.t) (row   :> Dom.node Js.t);
      (row, (value :> Dom_html.element Js.t), slider)
    in
    let px_to_str f = Printf.sprintf "%d px" (int_of_float f) in

    (* River height *)
    let (_r1, v1, s1) = add_row p "River height (px)" in
    set_attr s1 "min" "0"; set_attr s1 "max" "240"; set_attr s1 "step" "5";
    set_attr s1 "value" (string_of_int (int_of_float !(Params.river_h)));
    v1##.textContent := Js.Opt.return (Js.string (px_to_str !(Params.river_h)));
    Lwt.async (fun () -> Lwt_js_events.inputs s1 (fun _ _ ->
      let v = float_of_string (Js.to_string s1##.value) in
      Params.river_h := v; Bands.set_heights ();
      v1##.textContent := Js.Opt.return (Js.string (px_to_str v)); Lwt.return_unit));

    (* Hospital height *)
    let (_r2, v2, s2) = add_row p "Hospital height (px)" in
    set_attr s2 "min" "40"; set_attr s2 "max" "300"; set_attr s2 "step" "5";
    set_attr s2 "value" (string_of_int (int_of_float !(Params.hospital_h)));
    v2##.textContent := Js.Opt.return (Js.string (px_to_str !(Params.hospital_h)));
    Lwt.async (fun () -> Lwt_js_events.inputs s2 (fun _ _ ->
      let v = float_of_string (Js.to_string s2##.value) in
      Params.hospital_h := v; Bands.set_heights ();
      v2##.textContent := Js.Opt.return (Js.string (px_to_str v)); Lwt.return_unit));

    (* Max creets *)
    let (_r3, v3, s3) = add_row p "Max creets" in
    set_attr s3 "min" "10"; set_attr s3 "max" "120"; set_attr s3 "step" "1";
    set_attr s3 "value" (string_of_int !(Params.max_creets));
    v3##.textContent := Js.Opt.return (Js.string (string_of_int !(Params.max_creets)));
    Lwt.async (fun () -> Lwt_js_events.inputs s3 (fun _ _ ->
      let v = int_of_string (Js.to_string s3##.value) in
      Params.max_creets := v;
      v3##.textContent := Js.Opt.return (Js.string (string_of_int v)); Lwt.return_unit));

    (* Initial creets *)
    let (_r4, v4, s4) = add_row p "Initial creets (at Play)" in
    set_attr s4 "min" "4"; set_attr s4 "max" "40"; set_attr s4 "step" "1";
    set_attr s4 "value" (string_of_int !(Params.initial_creets));
    v4##.textContent := Js.Opt.return (Js.string (string_of_int !(Params.initial_creets)));
    Lwt.async (fun () -> Lwt_js_events.inputs s4 (fun _ _ ->
      let v = int_of_string (Js.to_string s4##.value) in
      Params.initial_creets := v;
      v4##.textContent := Js.Opt.return (Js.string (string_of_int v)); Lwt.return_unit));
    ()
end

(* ─────────────────────────────────────────────────────────────────────────── *)
module%client Overlay = struct
  open Js_of_ocaml

  let init_bands () = Bands.init ()

  let init_pause_button () =
    let btn =
      match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "btn-pause")) with
      | Some e -> Js.Opt.get (Dom_html.CoerceTo.button e) (fun () -> assert false)
      | None ->
          let open Js_of_ocaml_tyxml.Tyxml_js in
          let b = Html.button ~a:[ Html.a_id "btn-pause"; Html.a_class ["btn"; "btn--pause"] ] [ Html.txt "" ] in
          let dom = Js_of_ocaml_tyxml.Tyxml_js.To_dom.of_button b in
          Dom.appendChild (Dom_html.document##.body :> Dom.node Js.t) (dom :> Dom.node Js.t);
          dom
    in
    let open Js_of_ocaml_lwt in
    let update_icon () =
      (* İkonu CSS sınıflarıyla değiştiriyoruz *)
      if !(Config.paused) then btn##.classList##add (Js.string "is-paused")
      else btn##.classList##remove (Js.string "is-paused")
    in
    update_icon ();
    Lwt.async (fun () ->
      Lwt_js_events.clicks btn (fun _ _ ->
        if !(Runtime.game_started) then (
          Config.paused := not !(Config.paused);
          if !(Config.paused) then Timer.pause () else Timer.resume ();
          update_icon ()
        ); Lwt.return_unit))

  let ensure_settings_panel () =
    match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "settings-panel")) with
    | Some e -> Js.Opt.get (Dom_html.CoerceTo.div e) (fun () -> assert false)
    | None ->
        let dv = Dom_html.createDiv Dom_html.document in
        dv##.id := Js.string "settings-panel";
        dv##.className := Js.string "settings is-hidden";
        Dom.appendChild (Dom_html.document##.body :> Dom.node Js.t) (dv :> Dom.node Js.t);
        dv

  let init_menu_button () =
    let btn =
      match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "btn-menu")) with
      | Some e -> Js.Opt.get (Dom_html.CoerceTo.button e) (fun () -> assert false)
      | None ->
          let open Js_of_ocaml_tyxml.Tyxml_js in
          let b = Html.button ~a:[ Html.a_id "btn-menu"; Html.a_title "Settings"; Html.a_class ["btn"; "btn--menu"] ] [ Html.txt "" ] in
          let dom = Js_of_ocaml_tyxml.Tyxml_js.To_dom.of_button b in
          Dom.appendChild (Dom_html.document##.body :> Dom.node Js.t) (dom :> Dom.node Js.t);
          dom
    in
    let panel = ensure_settings_panel () in
    (* İçeride ayrıca bir Close butonu *)
    (match Js.Opt.to_option (panel##querySelector (Js.string ".settings__close")) with
     | Some _ -> ()
     | None ->
         let closeb = Dom_html.createButton Dom_html.document in
         closeb##.className := Js.string "settings__close";
         closeb##.title := Js.string "Close";
         Dom.appendChild (panel :> Dom.node Js.t) (closeb :> Dom.node Js.t));

    let close_btn = Js.Opt.get (panel##querySelector (Js.string ".settings__close")) (fun () -> assert false) in
    let set_open open_ =
      if open_ then (panel##.classList##remove (Js.string "is-hidden"); btn##.classList##add (Js.string "is-open"))
      else (panel##.classList##add (Js.string "is-hidden"); btn##.classList##remove (Js.string "is-open"))
    in
    (* İlk kez açılıyorsa sliderları oluştur *)
    if panel##.childNodes##.length <= 1 then Settings.make_sliders panel;

    let open Js_of_ocaml_lwt in
    Lwt.async (fun () ->
      Lwt_js_events.clicks btn (fun _ _ ->
        let now_open =
          if Js.to_bool (panel##.classList##contains (Js.string "is-hidden"))
          then true else false
        in
        set_open now_open; Lwt.return_unit));

    Lwt.async (fun () ->
      Lwt_js_events.clicks (Js.Opt.get (Dom_html.CoerceTo.button close_btn) (fun () -> assert false))
        (fun _ _ -> set_open false; Lwt.return_unit));
    ()

  (* Play overlay: arka plan blur, Play’e basınca başlar *)
  let ensure_play_overlay () =
    match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "play-overlay")) with
    | Some e -> Js.Opt.get (Dom_html.CoerceTo.div e) (fun () -> assert false)
    | None ->
        let open Js_of_ocaml_tyxml.Tyxml_js in
        let overlay =
          Html.div ~a:[ Html.a_id "play-overlay"; Html.a_class ["overlay"; "overlay--play"] ] [
            Html.div ~a:[ Html.a_class ["overlay__box"] ] [
              Html.button ~a:[ Html.a_id "btn-play"; Html.a_class ["btn"; "btn--primary"] ] [ Html.txt "Play" ]
            ]
          ]
        in
        let dom = Js_of_ocaml_tyxml.Tyxml_js.To_dom.of_div overlay in
        Dom.appendChild (Dom_html.document##.body :> Dom.node Js.t) (dom :> Dom.node Js.t);
        dom

  let show_play_blur () =
    (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "sim")) with
     | Some sim -> sim##.classList##add (Js.string "is-blurred")
     | None -> ())
  let hide_play_blur () =
    (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "sim")) with
     | Some sim -> sim##.classList##remove (Js.string "is-blurred")
     | None -> ())

  let init_play (on_play: unit -> unit) =
    let overlay = ensure_play_overlay () in
    show_play_blur ();
    let btn = Js.Opt.get (Dom_html.document##getElementById (Js.string "btn-play")) (fun () -> assert false) in
    let open Js_of_ocaml_lwt in
    Lwt.async (fun () ->
      Lwt_js_events.clicks (Js.Opt.get (Dom_html.CoerceTo.button btn) (fun () -> assert false))
        (fun _ _ ->
           overlay##.classList##add (Js.string "is-hidden");
           hide_play_blur ();
           on_play ();
           Lwt.return_unit))
end

module%client Game = struct
  open Js_of_ocaml

  let start () =
    if not !(Runtime.game_started) then (
      Runtime.game_started := true;
      Difficulty.start ();
      Stats.refresh ();
      Input.install ();
      Timer.start ();
      Collider.start ();
      Random.self_init ();
      let w = float_of_int Dom_html.window##.innerWidth
      and h = float_of_int Dom_html.window##.innerHeight in
      for i=1 to !(Params.initial_creets) do
        let x = Random.float (max 1. (w -. Const.base_size)) in
        let y = Random.float (max 1. (h -. Const.base_size)) in
        let c = Creet.create ~id:i ~x ~y () in
        World.add c; Movement.start c; Movement.start_reproduction c;
      done;
    )

  let replay () =
    (match Js.Opt.to_option (Dom_html.document##getElementById (Js.string "gameover")) with
     | Some g -> Js.Opt.iter g##.parentNode (fun p -> ignore (Dom.removeChild p (g :> Dom.node Js.t)))
     | None -> ());
    Session.epoch := !Session.epoch + 1;
    World.all () |> List.iter (fun c ->
      Js.Opt.iter c.Creet.elt##.parentNode (fun p -> ignore (Dom.removeChild p (c.Creet.elt :> Dom.node Js.t))));
    World.creets := [];
    Stats.dead_total := 0; Stats.refresh ();
    Config.paused := false; Runtime.game_over := false; Runtime.game_started := true;
    Difficulty.base := 1.0; Timer.start (); Collider.start ();
    let w = float_of_int Dom_html.window##.innerWidth and h = float_of_int Dom_html.window##.innerHeight in
    Random.self_init ();
    for i=1 to !(Params.initial_creets) do
      let x = Random.float (max 1. (w -. Const.base_size)) in
      let y = Random.float (max 1. (h -. Const.base_size)) in
      let c = Creet.create ~id:i ~x ~y () in
      World.add c; Movement.start c; Movement.start_reproduction c;
    done
end

(* ─────────────────────────────────────────────────────────────────────────── *)
let%shared () =
  App.register ~service:main_service (fun () () ->
    Lwt.return
      Eliom_content.Html.F.(
        html
          (head
             (title (txt "h42n42"))
             [ css_link
                 ~uri:(make_uri
                         ~service:(Eliom_service.static_dir ())
                         ["css"; "h42n42.css"])
                 () ])
          (body [ div ~a:[a_id "sim"] [] ]))
  )

(* ─────────────────────────────────────────────────────────────────────────── *)
let%client _ =
  Lwt.async (fun () ->
    let%lwt _ = Js_of_ocaml_lwt.Lwt_js_events.onload () in
    Overlay.init_bands ();
    Stats.refresh ();
    Overlay.init_pause_button ();
    Overlay.init_menu_button ();
    Callbacks.on_replay := (fun () -> Game.replay ());

    (* Uygulama Play overlay ile başlar *)
    Overlay.init_play (fun () -> Game.start ());
    Lwt.return_unit
  )
