(* This file was generated by Eliom-distillery.
   Feel free to use it, modify it, and redistribute it as you wish. *)

   let%server application_name = "h42n42"
   let%client application_name = Eliom_client.get_application_name ()
   
   let%server () =
     Ocsipersist_settings.set_db_file "local/var/data/h42n42/h42n42_db"
   
   module%shared App = Eliom_registration.App (struct
     let application_name = application_name
     let global_data_path = Some ["__global_data__"]
   end)
   
   let%client _ = Eliom_client.persist_document_head ()
   
   let%server main_service =
     Eliom_service.create
       ~path:(Eliom_service.Path [])
       ~meth:(Eliom_service.Get Eliom_parameter.unit)
       ()
   
   let%client main_service = ~%main_service
   
   let%shared () =
     App.register ~service:main_service (fun () () ->
       Lwt.return
         Eliom_content.Html.F.(
           html
             (head
                (title (txt "h42n42"))
                [ css_link ~uri:(make_uri ~service:(Eliom_service.static_dir ()) ["css"; "h42n42.css"])()]
                )
             (body
                [ h1 [txt "Welcome to h42n42 beeligul!"]
                ; div
                    ~a: [ a_id "hospital"]
                    []
                (* buraya script etiketleri gelecek *)
                ; script
                     ~a:[ a_src (make_uri ~service:(Eliom_service.static_dir ()) ["js"; "h42n42.js"]) ]
                    (cdata "")
                ; script
                     ~a:[ a_src (make_uri ~service:(Eliom_service.static_dir ()) ["js"; "movement.js"]) ]
                    (cdata "")
              ]
             )
         )
     )
   